- main.tf
https://tools.hmcts.net/jira/browse/DTSPO-172
> DTSPO-172 Added path.module

- main.tf
> Add nonprod env

- main.tf
https://tools.hmcts.net/jira/browse/DTSPO-1918
Added criticality.
```
[ ] Yes
[ ] No
```
> Added criticality.

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-380
Added config for CFT Platform
```
[ ] Yes
[x ] No
```
> DTSPO-380 CFT Platform Config

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-1727
Added team config for SOC. 
Build notice slack channel left blank - they don't have one.
```
[ ] Yes
[x ] No
```
> DTSPO-1727  SOC Team Config

- team-config.yml
> Dtspo-1152: added an entry for acme application. 

- team-config.yml
> Dtspo-1152: Added new products 

- team-config.yml
Dtspo-2879: Jenkins application
> Dtspo-2879: Jenkins installation 

- main.tf
> Dtspo-2879: Added new env 

- team-config.yml
> Add mailrelay team config

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-382
Adding entry for HMI team
```
[ ] Yes
[x] No
```
> DTSPO-382: Adding entry for HMI

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-382
Adding additional entries to team config for sharedservices aks infrastructure
```
[ ] Yes
[x] No
```
> DTSPO-382: Updating team entry

- team-config.yml
Adding Pip team config
```
[ ] Yes
[ x] No
```
> adding team config for pip

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-382
Adding CVP application entry for compliance tagging
```
[ ] Yes
[x] No
```
> DTSPO-382: Adding entry for cvp

- main.tf
https://tools.hmcts.net/jira/browse/DTSPO-4415
As part of this SPIKE, we are required to tag the vms using the common tags library. Adding an entry for Hub sbox
```
[ ] Yes
[x] No
```
> DTSPO-4415: Adding sandbox entry for hub resources

- main.tf
https://tools.hmcts.net/jira/browse/DTSPO-4415
Adding entries for other environments in rdo Hub.
```
[ ] Yes
[x] No
```
> DTSPO-4415: Adding entries for other hub envs

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-7842
Updated the application tag name for CVP to match cloud-video-platform within the agreed tagging dictionary here - https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1007945237#Taggingv0.4-TaggingDictionary
```
[ ] Yes
[x] No
```
> updated CVP application tag to agreed tag from tagging dictionary

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-7842
Updated the application tag name for Video Hearings to match video-hearings-service within the agreed tagging dictionary here - https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1007945237#Taggingv0.4-TaggingDictionary
```
[ ] Yes
[x] No
```
> updated Video Hearings  application tag to agreed tag from tagging dictionary

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-7853
Updated Hearings Management Interface tags to match agreed tag name within tagging dictionary - https://tools.hmcts.net/confluence/display/DCO/Tagging+v0.4
```
[ ] Yes
[x] No
```
> updated Hearings Management Interface tag to match tagging dictionary

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-7853
Updated Publishing information service tag to match agreed name shown within the tagging dictionary - https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1007945237#Taggingv0.4-TaggingDictionary
```
[ ] Yes
[x] No
```
> updated publishing information tag to match tagging dictionary

- team-config.yml
> Added missing tags/teams

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-7842
Added small systems migration service tag and update heritage application tag to bais as per tagging dictionary.
```
[ ] Yes
[x] No
```
> added smallsystems migrations team config

- team-config.yml
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> Added common tags for RCJ Apps

- team-config.yml
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/DTSPO-9049
Change description
Add team-config for core-infra
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
> DTSPO-9049 - Add core-infra team-config

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-9363
Adding Archiving with records management product.
```
[ ] Yes
[ x ] No
```
> feat: add archiving product

- team-config.yml
N/A
Shortening product name for archiving with records management.
```
[ ] Yes
[ x ] No
```
> fix: shorten archiving product name

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-9743
Add team config for azure-enterprise repo to utilise
```
[ ] Yes
[x] No
```
> DTSPO-9743 - Add enterprise team config

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-9017
Add PowerApp Config.
```
[ ] Yes
[ ] No
```
> Add PowerApp Config

- team-config.yml
Added config for MARTHA
```
[ ] Yes
[x] No
```
> feat: added martha team config

- main.tf
https://tools.hmcts.net/jira/browse/DTSPO-9746
Adding management/mgmt environment mapping to accommodate Reform-CFT-Mgmt subscription in hmcts/azure-enterprise
Resources related to this sub are currently in a resource group with the environment set to mgmt
```
[ ] Yes
[x] No
```
> DTSPO-9746 - add mgmt

- team-config.yml
Adding crime config, the initial commit may need tweaking
```
[ ] Yes
[x] No
```
> DTSPO-11031 - add config for crime

- main.tf
- output.tf
- variables.tf
[DTSPO-11424](https://tools.hmcts.net/jira/browse/DTSPO-11424)
Add auto-shutdown tag as an additional tag
```
[ ] Yes
[X] No
```
> DTSPO-11424: Add auto-shutdown tag

- README.md
- main.tf
- variables.tf
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[x ] No
```
> DTSPO-11787 sbox:  added expire tag 

- .terraform-docs.yml
- README.md
- main.tf
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[x ] No
```
> DTSPO-11787.  update Documentation

- team-config.yml
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> DTSPO-11874   adding new product

- team-config.yml
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> Add PRE to team-config.yaml

- team-config.yml
DTSPO-13908
Update application archive-records-management
```
[ ] Yes
[ X] No
```
> Update application archive-records-management

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-14508
Adds team config for AllPay application
```
[ ] Yes
[ ] No
```
> Add AllPay Team

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-15155
Added Crime-Portal
```
[ ] Yes
[x] No
```
> feat: added crime-portal

- README.md
- main.tf
- variables.tf
DTSPO-15113
Add new tag for startup
> Dtspo 15113

- team-config.yml
Add the data catalogue team to team-config.yml
```
[ ] Yes
[X] No
```
> Add data catalogue team to team-config.yml

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-16489
Add sdrs product tag.
> add sdrs product

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-14032
- Adding entry for docmosis to allow use of tags module in new infrastructure
> Adding docmosis entry to team-config.yml

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-17037
removing netbox app as its now deleted
> DTSPO-17037 - deleting netbox as its not needed

- team-config.yml
Noticed as part of https://github.com/hmcts/slack-help-bot/pull/418
> Add slack-help-bot

- team-config.yml
See [jira](https://tools.hmcts.net/jira/browse/DTSPO-22113)
Adding new application atlassian for tagging
> DTSPO-22113 - adding new atlassian application for tagging

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-22828
Added new application name and tags for the the DLRM Electoral Roll (ER) resources.
> DTSPO-22828 - added DLRM ER application tags

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-24632
Added tags for the CCD so that it will have correct tags on the new CCD infra.
> DTSPO-24632 - created CCD tags

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-25518
Adding gaps2 config to team-config file
> Adding gaps2 config to team-config file

- team-config.yml
https://tools.hmcts.net/jira/browse/DTSPO-25132
- Adding beetroot to team-config.yml
- Beetroot is being used to test changes to the terraform postgresql flexible module
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> DTSPO-25132: Adding beetroot to team-config.yml
